FROM pihole/pihole:dev
ARG TARGETARCH
ARG DEBIAN_FRONTEND="noninteractive"

RUN apt-get -y update && apt-get -y upgrade && apt-get -y install unbound unbound-anchor unbound-host dns-root-data jq wget curl xz-utils
COPY etc/ /etc/

#Not force update from git, only upstream decisions
#COPY update-* /usr/sbin/
#RUN /usr/sbin/update-core
#RUN /usr/sbin/update-web
#RUN /usr/sbin/update-ftl $TARGETARCH
#RUN /usr/sbin/update-s6 $TARGETARCH

RUN chown -R root:unbound /etc/unbound && chmod 640 /etc/unbound/unbound.conf.d/* /etc/unbound/zones/*
#RUN chmod 777 /etc/cont-init.d/*
RUN unbound-anchor -v || unbound-anchor -v

