#!/bin/bash
ARCH=$1
source /etc/pi-hole-versions

URLBASE="https://github.com/pi-hole/FTL/releases/download/$FTL_VERSION"
echo "Update FTL to $FTL_VERSION"
case $ARCH in
	arm)
		URL="$URLBASE/pihole-FTL-armv7-linux-gnueabihf"
	;;
	arm64)
		URL="$URLBASE/pihole-FTL-aarch64-linux-gnu"
	;;
	amd64) 
		URL="$URLBASE/pihole-FTL-linux-x86_64"
        ;;
esac
echo "URL $URL"

wget "$URL" -q -O /usr/bin/pihole-FTL
chmod 755 /usr/bin/pihole-FTL