#!/usr/bin/with-contenv bash
set -e

if [ -n $DOT_UPSTREAM ]
then
	case $DOT_UPSTREAM in
	cloudflare)
		FORWARDS=1.1.1.1,1.0.0.1
		;;
	google)
	        FORWARDS=8.8.8.8,8.4.4.8
	        ;;
	quad9-secure)
	        FORWARDS=9.9.9.9
	        ;;
	quad9-insecure)
	        FORWARDS=9.9.9.10
	        ;;
	adguard)
	        FORWARDS=176.103.130.130,176.103.130.131
	        ;;
	adguard-family)
	        FORWARDS=176.103.130.132,176.103.130.134
	        ;;
	adguard-nonfiltering)
	        FORWARDS=176.103.130.135,176.103.130.136
	        ;;
	cleanbrowsing-security)
	        FORWARDS=185.228.168.9,185.228.169.9
	        ;;
	cleanbrowsing-family)
	        FORWARDS=185.228.168.168,185.228.169.168
	        ;;
	cleanbrowsing-security)
	        FORWARDS=185.228.168.10,185.228.168.11
	        ;;
	comcast)
	        FORWARDS=96.113.151.145
	        ;;
	dnssb)
	        FORWARDS=185.222.222.222,185.184.222.222
	        ;;
	pumplex)	
			FORWARDS=51.38.83.141
			;;		
	*)
		FORWARDS=$DOT_UPSTREAM
		;;
	esac
else
	FORWARDS=1.1.1.1,1.0.0.1
fi

for FORWARD in ${FORWARDS//,/ }
do
	echo "     forward-addr: $FORWARD@853" >> /etc/unbound/forward-dot-user.conf
done

cp /etc/unbound/forward-dot-user.conf /etc/unbound/unbound.conf.d/forward-dot-user.conf

echo "  Running Unbound at 127.0.0.1#5353 upstream to $FORWARDS"

unbound
